### ISSUE TITLE
maintainers not crawling correctly

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/integrations#11]
@pio Seems maintainers is being crawled by last person who commited perhaps rather than who is maintaining. Not sure but in prismic the maintainer is Sebastien and Lihbr but is showing James Pegg.

https://deploy-preview-605--nuxt.netlify.app/with/prismic

**Comment by pi0** [comment]
@debs-obrien It is not crawled but manual process. Only for 3rd parties we use org/username as default. Anyone with publish access should be maintainer will fix

**Comment by pi0** [comment]
a9fa9bb769b9712d715b8bb7bcf56d37d062c859
