### ISSUE TITLE
content module reading from wrong module (monorepo support)

### ISSUE THREAD

**Issue by debs-obrien** [nuxt/integrations#7]
some of the links for content are reading from an old content module package. see the npm downloads button for example

https://deploy-preview-605--nuxt.netlify.app/integrations/content

**Comment by debs-obrien** [comment]
@pi0 let me know if this needs manual fixing or is a scraping issue

**Comment by pi0** [comment]
We need to support mono-repo paths. NPM is read from top level which is wrong.

**Comment by pi0** [comment]
Actually we already supported :D Repo has to be specified like this: `nuxt/content#master/packages/content`
